services:
  mongo:
    build: docker/mongo
    restart: always
    volumes:
      - data_mongo:/data/mongo
    ports:
      - ${MONGODB_PORT}:27017

  mongo-express:
      build: docker/mongo-express
      restart: always
      ports:
        - ${MONGO_EXPRESS_PORT}:8081
      environment:
        ME_CONFIG_MONGODB_SERVER: mongo
      depends_on:
        - mongo

  redis:
    build: docker/redis
    restart: always
    volumes:
      - data_redis:/data/redis
    ports:
      - ${REDIS_PORT}:6379

  elasticsearch:
    build: docker/elasticsearch
    restart: always
    volumes:
      - data_elastic:/data/elastic
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
    mem_limit: 1024M
    mem_reservation: 1024M
    ports:
      - ${ELASTICSEARCH_PORT}:9200

  kibana:
    build: docker/kibana
    restart: always
    volumes:
      - data_kibana:/data/kibana
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
    depends_on:
      - elasticsearch
    ports:
      - ${KIBANA_PORT}:5601

  rabbitmq:
    build: docker/rabbitmq
    restart: always
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_PANEL_PORT}:15672

volumes:
  data_mongo:
  data_redis:
  data_elastic:
  data_kibana: