services:
  rpg-mongo:
    build: docker/mongo
    restart: always
    volumes:
      - data_mongo:/data/mongo
    ports:
      - ${MONGODB_PORT}:27017

  rpg-mongo-express:
      build: docker/mongo-express
      restart: always
      ports:
        - ${MONGO_EXPRESS_PORT}:8081
      environment:
        ME_CONFIG_MONGODB_SERVER: rpg-mongo
      depends_on:
        - rpg-mongo

  rpg-redis:
    build: docker/redis
    restart: always
    volumes:
      - data_redis:/data/redis
    ports:
      - ${REDIS_PORT}:6379

  rpg-elasticsearch:
    build: docker/elasticsearch
    restart: always
    volumes:
      - data_elastic:/data/elastic
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
    ports:
      - ${ELASTICSEARCH_PORT}:9200

  rpg-kibana:
    build: docker/kibana
    restart: always
    depends_on:
      - rpg-elasticsearch
    ports:
      - ${KIBANA_PORT}:5601

volumes:
  data_mongo:
  data_redis:
  data_elastic: