import { chars as trans } from 'lang'

export default class {
    static keyCodeToChar: Record<number, keyof typeof this.keyCharToCode> = {
        1: 'Mouse Left',
        2: 'Mouse Right',
        4: 'Mouse Middle',
        5: 'Mouse 4',
        6: 'Mouse 5',
        8: 'Backspace',
        9: 'Tab',
        13: 'Enter',
        16: 'Shift',
        17: 'Ctrl',
        18: 'Alt',
        19: 'Pause/Break',
        20: 'Caps Lock',
        27: 'Esc',
        32: 'Space',
        33: 'Page Up',
        34: 'Page Down',
        35: 'End',
        36: 'Home',
        37: 'Left',
        38: 'Up',
        39: 'Right',
        40: 'Down',
        45: 'Insert',
        46: 'Delete',
        48: '0',
        49: '1',
        50: '2',
        51: '3',
        52: '4',
        53: '5',
        54: '6',
        55: '7',
        56: '8',
        57: '9',
        65: 'A',
        66: 'B',
        67: 'C',
        68: 'D',
        69: 'E',
        70: 'F',
        71: 'G',
        72: 'H',
        73: 'I',
        74: 'J',
        75: 'K',
        76: 'L',
        77: 'M',
        78: 'N',
        79: 'O',
        80: 'P',
        81: 'Q',
        82: 'R',
        83: 'S',
        84: 'T',
        85: 'U',
        86: 'V',
        87: 'W',
        88: 'X',
        89: 'Y',
        90: 'Z',
        91: 'Windows',
        93: 'Right Click',
        96: 'Numpad 0',
        97: 'Numpad 1',
        98: 'Numpad 2',
        99: 'Numpad 3',
        100: 'Numpad 4',
        101: 'Numpad 5',
        102: 'Numpad 6',
        103: 'Numpad 7',
        104: 'Numpad 8',
        105: 'Numpad 9',
        106: 'Numpad *',
        107: 'Numpad +',
        109: 'Numpad -',
        110: 'Numpad .',
        111: 'Numpad /',
        112: 'F1',
        113: 'F2',
        114: 'F3',
        115: 'F4',
        116: 'F5',
        117: 'F6',
        118: 'F7',
        119: 'F8',
        120: 'F9',
        121: 'F10',
        122: 'F11',
        123: 'F12',
        144: 'Num Lock',
        145: 'Scroll Lock',
        182: 'My Computer',
        183: 'My Calculator',
        186: ';',
        187: '=',
        188: ',',
        189: '-',
        190: '.',
        191: '/',
        192: '`',
        219: '[',
        220: '\\',
        221: ']',
        222: "'",
    }

    static keyCharToCode = {
        'Mouse Left': 1,
        'Mouse Right': 2,
        'Mouse Middle': 4,
        'Mouse 4': 5,
        'Mouse 5': 6,
        Backspace: 8,
        Tab: 9,
        Enter: 13,
        Shift: 16,
        Ctrl: 17,
        Alt: 18,
        'Pause/Break': 19,
        'Caps Lock': 20,
        Esc: 27,
        Space: 32,
        'Page Up': 33,
        'Page Down': 34,
        End: 35,
        Home: 36,
        Left: 37,
        Up: 38,
        Right: 39,
        Down: 40,
        Insert: 45,
        Delete: 46,
        '0': 48,
        '1': 49,
        '2': 50,
        '3': 51,
        '4': 52,
        '5': 53,
        '6': 54,
        '7': 55,
        '8': 56,
        '9': 57,
        A: 65,
        B: 66,
        C: 67,
        D: 68,
        E: 69,
        F: 70,
        G: 71,
        H: 72,
        I: 73,
        J: 74,
        K: 75,
        L: 76,
        M: 77,
        N: 78,
        O: 79,
        P: 80,
        Q: 81,
        R: 82,
        S: 83,
        T: 84,
        U: 85,
        V: 86,
        W: 87,
        X: 88,
        Y: 89,
        Z: 90,
        Windows: 91,
        'Right Click': 93,
        'Numpad 0': 96,
        'Numpad 1': 97,
        'Numpad 2': 98,
        'Numpad 3': 99,
        'Numpad 4': 100,
        'Numpad 5': 101,
        'Numpad 6': 102,
        'Numpad 7': 103,
        'Numpad 8': 104,
        'Numpad 9': 105,
        'Numpad *': 106,
        'Numpad +': 107,
        'Numpad -': 109,
        'Numpad .': 110,
        'Numpad /': 111,
        F1: 112,
        F2: 113,
        F3: 114,
        F4: 115,
        F5: 116,
        F6: 117,
        F7: 118,
        F8: 119,
        F9: 120,
        F10: 121,
        F11: 122,
        F12: 123,
        'Num Lock': 144,
        'Scroll Lock': 145,
        'My Computer': 182,
        'My Calculator': 183,
        ';': 186,
        '=': 187,
        ',': 188,
        '-': 189,
        '.': 190,
        '/': 191,
        '`': 192,
        '[': 219,
        '\\': 220,
        ']': 221,
        "'": 222,
    }

    static translatedKeyCodes: Record<keyof typeof this.keyCharToCode, string> = {
        'Mouse Left': trans.mouseLeft,
        'Mouse Right': trans.mouseRight,
        'Mouse Middle': trans.mouseMiddle,
        'Mouse 4': trans.mouse4,
        'Mouse 5': trans.mouse5,
        Backspace: 'Backspace',
        Tab: 'Tab',
        Enter: 'Enter',
        Shift: 'Shift',
        Ctrl: 'Ctrl',
        Alt: 'Alt',
        'Pause/Break': 'Pause/Break',
        'Caps Lock': 'Caps Lock',
        Esc: 'Esc',
        Space: trans.space,
        'Page Up': 'Page Up',
        'Page Down': 'Page Down',
        End: 'End',
        Home: 'Home',
        Left: trans.arrowLeft,
        Up: trans.arrowUp,
        Right: trans.arrowRight,
        Down: trans.arrowDown,
        Insert: 'Insert',
        Delete: 'Delete',
        '0': '0',
        '1': '1',
        '2': '2',
        '3': '3',
        '4': '4',
        '5': '5',
        '6': '6',
        '7': '7',
        '8': '8',
        '9': '9',
        A: 'A',
        B: 'B',
        C: 'C',
        D: 'D',
        E: 'E',
        F: 'F',
        G: 'G',
        H: 'H',
        I: 'I',
        J: 'J',
        K: 'K',
        L: 'L',
        M: 'M',
        N: 'N',
        O: 'O',
        P: 'P',
        Q: 'Q',
        R: 'R',
        S: 'S',
        T: 'T',
        U: 'U',
        V: 'V',
        W: 'W',
        X: 'X',
        Y: 'Y',
        Z: 'Z',
        Windows: 'Windows',
        'Right Click': trans.mouseRight,
        'Numpad 0': 'Numpad 0',
        'Numpad 1': 'Numpad 1',
        'Numpad 2': 'Numpad 2',
        'Numpad 3': 'Numpad 3',
        'Numpad 4': 'Numpad 4',
        'Numpad 5': 'Numpad 5',
        'Numpad 6': 'Numpad 6',
        'Numpad 7': 'Numpad 7',
        'Numpad 8': 'Numpad 8',
        'Numpad 9': 'Numpad 9',
        'Numpad *': 'Numpad *',
        'Numpad +': 'Numpad +',
        'Numpad -': 'Numpad -',
        'Numpad .': 'Numpad .',
        'Numpad /': 'Numpad /',
        F1: 'F1',
        F2: 'F2',
        F3: 'F3',
        F4: 'F4',
        F5: 'F5',
        F6: 'F6',
        F7: 'F7',
        F8: 'F8',
        F9: 'F9',
        F10: 'F10',
        F11: 'F11',
        F12: 'F12',
        'Num Lock': 'Num Lock',
        'Scroll Lock': 'Scroll Lock',
        'My Computer': trans.myComputer,
        'My Calculator': trans.myCalculator,
        ';': ';',
        '=': '=',
        ',': ',',
        '-': '-',
        '.': '.',
        '/': '/',
        '`': '`',
        '[': '[',
        '\\': '\\',
        ']': ']',
        "'": "'",
    }

    static getCharFromKeyCode(keyCode: number) {
        return this.keyCodeToChar[keyCode as keyof typeof this.keyCodeToChar]
    }

    static getKeyCodeFromChar(char: string) {
        return this.keyCharToCode[char as keyof typeof this.keyCharToCode]
    }

    static getTranslatedChar(char: string) {
        return this.translatedKeyCodes[char as keyof typeof this.keyCharToCode]
    }

    static getTranslatedCharFromKeyCode(keyCode: number): string {
        const char = this.getCharFromKeyCode(keyCode)
        return this.translatedKeyCodes[char]
    }
}
